app.datasource.url=jdbc:postgresql://localhost:5434/sigmaql
app.datasource.username=postgres
app.datasource.password=ilikepizza
app.datasource.driver-class-name=org.postgresql.Driver

query.datasource.url=jdbc:postgresql://localhost:5433/test_aleks
query.datasource.username=postgres
query.datasource.password=1234
query.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
jwt.secret=The_quick_brown_fox_jumps_over_the_lazy_dog