spring.config.import=optional:classpath:env.properties

app.datasource.url=${APP_DATASOURCE_URL:}
app.datasource.username=${APP_DATASOURCE_USERNAME:}
app.datasource.password=${APP_DATASOURCE_PASSWORD:}
app.datasource.driver-class-name=${APP_DATASOURCE_DRIVER:org.postgresql.Driver}

query.datasource.url=${QUERY_DATASOURCE_URL:}
query.datasource.username=${QUERY_DATASOURCE_USERNAME:}
query.datasource.password=${QUERY_DATASOURCE_PASSWORD:}
query.datasource.driver-class-name=${QUERY_DATASOURCE_DRIVER:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${SERVER_PORT:8080}
jwt.secret=${JWT_SECRET:}
