services:
  postgres:
    image: postgres:16
    container_name: sigmaql
    environment:
      POSTGRES_DB: sigmaql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ilikepizza
    ports:
      - "5434:5432"